//
//  FeatureParityTests.swift
//  WristWatcher Watch AppTests
//
//  The D2 correctness argument. FeatureExtractor and the thesis repo's
//  pilot/analysis/lib/features.py must compute the same 36 numbers in the same
//  order, because the D5 Core ML model is fitted on the latter and asks no
//  questions about its input.
//
//  parity_fixture.json is generated by tools/parity.py, which imports
//  and RUNS the thesis code rather than reimplementing it. What is asserted
//  here is therefore Swift against the actual training pipeline, not Swift
//  against a second opinion about it.
//
//  If this fails, do not adjust the tolerance. See docs/FEATURE-CONTRACT.md §7.1
//  for why every error class this guards against misses by many orders of
//  magnitude.
//

import XCTest
@testable import WristWatcher_Watch_App

final class FeatureParityTests: XCTestCase {
    private struct Fixture: Decodable {
        let windowLength: Int
        let stride: Int
        let featureNames: [String]
        let columns: [String]
        let samples: [[Double]]
        let windowStarts: [Int]
        let expected: [[Double]]
    }

    /// `TEST_RUNNER_PARITY_FIXTURE=/path/to/....parity.json` runs this suite against
    /// a real collector rehearsal CSV's fixture instead of the committed
    /// synthetic one — the D2 gate's "full collector rehearsal CSV" clause.
    /// The path is passed in rather than committed because no participant CSV,
    /// and nothing derived from one, may enter this repo (CLAUDE.md).
    ///
    /// The `TEST_RUNNER_` prefix is not optional — xcodebuild forwards only
    /// prefixed variables to the test process, and a bare `PARITY_FIXTURE`
    /// silently falls back to the bundled fixture and passes. Check the window
    /// count in `testFeaturesMatchPythonForEveryWindow`'s log line to see which
    /// fixture actually ran.
    private lazy var fixture: Fixture = {
        let override = ProcessInfo.processInfo.environment["PARITY_FIXTURE"]
        let url = override.map { URL(fileURLWithPath: $0) }
            ?? Bundle(for: Self.self).url(forResource: "parity_fixture", withExtension: "json")!
        let decoder = JSONDecoder()
        decoder.keyDecodingStrategy = .convertFromSnakeCase
        return try! decoder.decode(Fixture.self, from: Data(contentsOf: url))
    }()

    // MARK: - The contract itself

    /// The fixture was generated against these constants. If they drift apart,
    /// every other assertion here is comparing the wrong things and passing.
    func testFixtureAgreesWithContractConstants() {
        XCTAssertEqual(fixture.windowLength, FeatureExtractor.windowLength)
        XCTAssertEqual(fixture.stride, FeatureExtractor.stride)
        XCTAssertEqual(fixture.columns, ["timestamp"] + FeatureExtractor.channelNames)
    }

    /// Stat-major, channel-minor — FEATURE-CONTRACT.md §4. Asserted against
    /// `features.feature_names`' own output, so a channel-blocked layout fails
    /// here by name before it can fail by value.
    func testVectorLayoutMatchesPython() {
        XCTAssertEqual(fixture.featureNames, FeatureExtractor.featureNames)
        XCTAssertEqual(FeatureExtractor.featureNames.count, 36)
        XCTAssertTrue(FeatureExtractor.featureNames.prefix(9).allSatisfy { $0.hasSuffix("_mean") },
                      "first 9 features must be the 9 means, not grav_x's 4 statistics")
    }

    // MARK: - Windowing

    /// On a single-bout stream the ring's emissions are exactly
    /// `windowing.window_indices(win: 200, hop: 100)`.
    ///
    /// Single-bout only, and the restriction is real rather than convenient.
    /// Python restarts its window grid at every bout, so a 7-posture recording
    /// gives starts like 3645, 3745, ...; the ring is stride-aligned from the
    /// first sample forever, so it gives 3600, 3700, ... Neither contains the
    /// other and neither is wrong — `windowing.py` refuses to let a training
    /// window straddle two postures, while a live wrist has no bout boundaries
    /// to straddle. The grids can only be compared where there is one bout,
    /// which is the synthetic fixture and is also what the device produces.
    func testRingBufferMatchesPythonExactlyOnASingleBout() throws {
        try XCTSkipIf(ProcessInfo.processInfo.environment["PARITY_FIXTURE"] != nil,
                      "override fixture may be multi-bout; the grids need not agree")
        XCTAssertEqual(emittedWindows().map(\.start), fixture.windowStarts)
    }

    // MARK: - Parity

    func testFeaturesMatchPythonForEveryWindow() {
        // Python's own window starts, not the ring's emissions: which windows
        // exist is the bout rule's business (tested above), and this test is
        // about what the 36 numbers are once a window exists.
        let windows = fixture.windowStarts.map { start in
            (start: start, samples: Array(samples[start..<start + FeatureExtractor.windowLength]))
        }
        XCTAssertEqual(windows.count, fixture.expected.count)
        XCTAssertGreaterThan(windows.count, 0)
        // Says which fixture actually ran: the committed synthetic one is 7
        // windows, a real recording is hundreds.
        print("parity: \(windows.count) windows x \(FeatureExtractor.featureCount) features")

        for (w, window) in windows.enumerated() {
            guard let got = FeatureExtractor.extract(window.samples) else {
                return XCTFail("window \(w) refused as non-finite; the fixture is all finite")
            }
            let want = fixture.expected[w]
            XCTAssertEqual(got.count, want.count)

            // Per-channel scale, so a channel that lives at 1e-8 (uacc_z) is
            // held to its own magnitude rather than to 1.0, and a statistic
            // that is exactly 0.0 in Python (grav_x's SD — the channel is
            // constant) is not compared at zero tolerance. Channel index is
            // `i % 9` because the layout is stat-major.
            for i in 0..<want.count {
                let channel = i % FeatureExtractor.channelNames.count
                let scale = window.samples
                    .map { abs(Self.channelValue($0, channel)) }
                    .max() ?? 1
                let tolerance = 1e-12 * max(abs(want[i]), scale)
                XCTAssertEqual(got[i], want[i], accuracy: tolerance,
                               "window \(w), \(fixture.featureNames[i])")
            }
        }
    }

    // MARK: - Non-finite refusal (FEATURE-CONTRACT.md §6)

    /// Not fixture-driven: `features.extract` raises on non-finite input, so
    /// Python cannot produce an expected vector for this case. The behaviour
    /// being matched is the raise, not a value.
    func testNonFiniteWindowIsRefusedNotImputed() {
        let clean = Array(samples[0..<FeatureExtractor.windowLength])
        XCTAssertNotNil(FeatureExtractor.extract(clean))

        for bad in [Double.nan, .infinity, -.infinity] {
            var samples = clean
            let victim = samples[137]
            samples[137] = MotionSample(
                timestamp: victim.timestamp,
                gravity: (victim.gravity.x, bad, victim.gravity.z),
                userAcceleration: victim.userAcceleration,
                rotationRate: victim.rotationRate
            )
            XCTAssertNil(FeatureExtractor.extract(samples), "\(bad) must drop the window")
        }
    }

    // MARK: - Helpers

    /// The fixture's sample stream as `MotionSample`s, in file order.
    private lazy var samples: [MotionSample] = fixture.samples.map {
        MotionSample(timestamp: $0[0],
                     gravity: ($0[1], $0[2], $0[3]),
                     userAcceleration: ($0[4], $0[5], $0[6]),
                     rotationRate: ($0[7], $0[8], $0[9]))
    }

    private func emittedWindows() -> [(start: Int, samples: [MotionSample])] {
        var out: [(start: Int, samples: [MotionSample])] = []
        var index = 0
        let buffer = RingBuffer<MotionSample>(length: FeatureExtractor.windowLength,
                                              stride: FeatureExtractor.stride)
        buffer.onWindow = { window in
            out.append((start: index - FeatureExtractor.windowLength, samples: window))
        }
        for sample in samples {
            index += 1  // before push: onWindow reads it as the count pushed so far
            buffer.push(sample)
        }
        return out
    }

    private static func channelValue(_ s: MotionSample, _ channel: Int) -> Double {
        switch channel {
        case 0: return s.gravity.x
        case 1: return s.gravity.y
        case 2: return s.gravity.z
        case 3: return s.userAcceleration.x
        case 4: return s.userAcceleration.y
        case 5: return s.userAcceleration.z
        case 6: return s.rotationRate.x
        case 7: return s.rotationRate.y
        default: return s.rotationRate.z
        }
    }
}
